"""
This type stub file was generated by pyright.
"""

from argostranslate.models import ILanguageModel

class LibreTranslateAPI:
    """Connect to the LibreTranslate API"""
    DEFAULT_URL = ...
    def __init__(self, url: str = ..., api_key: str = ...) -> None:
        """Create a LibreTranslate API connection.

        Args:
            url: The url of the LibreTranslate endpoint.
            api_key: The API key.
        """
        ...
    
    def translate(self, q: str, source: str = ..., target: str = ...) -> str:
        """Translate string

        Args:
            q: The text to translate
            source: The source language code (ISO 639)
            target: The target language code (ISO 639)

        Returns: The translated text
        """
        ...
    
    def languages(self): # -> Any:
        """Retrieve list of supported languages.

        Returns: A list of available languages ex. [{"code":"en", "name":"English"}]
        """
        ...
    
    def detect(self, q: str): # -> Any:
        """Detect the language of a single text.

        Args:
            q: Text to detect

        Returns: The detected languages ex. [{"confidence": 0.6, "language": "en"}]
        """
        ...
    


class OpenAIAPI(ILanguageModel):
    def __init__(self, api_key: str) -> None:
        """Create an API connection.

        Args:
            api_key: The API key for the OpenAI API
        """
        ...
    
    def infer(self, prompt: str) -> str | None:
        """Connect to OpenAI API

        Args:
            prompt: The prompt to run inference on.

        Returns: The generated text
        """
        ...
    


