"""
This type stub file was generated by pyright.
"""

"""
Copyright (c) 2004-2020 Joerg Tiedemann

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
class BPE:
    def __init__(self, codes, merges=..., separator=..., vocab=..., glossaries=...) -> None:
        ...
    
    def process_line(self, line): # -> LiteralString:
        """segment line, dealing with leading and trailing whitespace"""
        ...
    
    def segment(self, sentence): # -> LiteralString:
        """segment single sentence (whitespace-tokenized string) with BPE encoding"""
        ...
    
    def segment_tokens(self, tokens): # -> list[Any]:
        """segment a sequence of tokens with BPE encoding"""
        ...
    


def create_parser(subparsers=...): # -> ArgumentParser:
    ...

def get_pairs(word): # -> set[Any]:
    """Return set of symbol pairs in a word.

    word is represented as tuple of symbols (symbols being variable-length strings)
    """
    ...

def encode(orig, bpe_codes, bpe_codes_reverse, vocab, separator, version, cache, glossaries=...): # -> tuple[Any] | list[Any] | tuple[Any, ...] | tuple[()] | tuple[*tuple[Any, ...], Literal['</w>']] | tuple[*tuple[Any, ...], Any]:
    """Encode word based on list of BPE merge operations, which are applied consecutively"""
    ...

def recursive_split(segment, bpe_codes, vocab, separator, final=...): # -> Generator[Any, Any, None]:
    """Recursively split segment into smaller units (by reversing BPE merges)
    until all units are either in-vocabulary, or cannot be split futher."""
    ...

def check_vocab_and_split(orig, bpe_codes, vocab, separator): # -> list[Any]:
    """Check for each segment in word if it is in-vocabulary,
    and segment OOV segments into smaller units by reversing the BPE merge operations"""
    ...

def read_vocabulary(vocab_file, threshold): # -> set[Any]:
    """read vocabulary file produced by get_vocab.py, and filter according to frequency threshold."""
    ...

def isolate_glossary(word, glossary): # -> list[Any] | list[str]:
    """
    Isolate a glossary present inside a word.

    Returns a list of subwords. In which all 'glossary' glossaries are isolated

    For example, if 'USA' is the glossary and '1934USABUSA' the word, the return value is:
        ['1934', 'USA', 'B', 'USA']
    """
    ...

if __name__ == "__main__":
    currentdir = ...
    newdir = ...
    parser = ...
    args = ...
    bpe = ...
