"""
This type stub file was generated by pyright.
"""

from argostranslate.package import AvailablePackage

def update_index(args): # -> None:
    """Update the package index."""
    ...

def get_available_packages() -> list[AvailablePackage]:
    """Get available packages and update packages list if it is not done

    Returns:
        The list of available packages
    """
    ...

def install_package_print_path(available_package: AvailablePackage): # -> None:
    ...

def install_all_packages(): # -> None:
    """Install all packages available to Argos Translate."""
    ...

def install_package(args): # -> None:
    """Install package."""
    ...

def search_packages(args): # -> None:
    """Display packages from remote index."""
    ...

def list_packages(args): # -> None:
    """List packages."""
    ...

def remove_package(args): # -> None:
    """Remove installed package."""
    ...

def main(): # -> None:
    """Run argospm command line program"""
    ...

