"""
This type stub file was generated by pyright.
"""

prompt = ...
def generate_prompt(text: str, from_name: str, from_code: str, to_name: str, to_code: str) -> str:
    ...

def parse_inference(output: str) -> str:
    ...

