"""
This type stub file was generated by pyright.
"""

class ILanguageModel:
    def infer(self, x: str) -> str | None:
        """Run language model on input x

        Args:
            x: Prompt to run inference on

        Returns:
            Output of inference
        """
        ...
    


