"""
This type stub file was generated by pyright.
"""

from pathlib import Path

USER_AGENT = ...
def get_protocol(url: str) -> str | None:
    """Gets the protocol of a URL string

    For example if url is "https://www.argosopentech.com" "https" is returned.
    If the protocol can't be determined None is returned

    Args:
        url: The URL to get the protocol of

    Returns:
        The string representation of the protocol or None
    """
    ...

supported_protocols = ...
def get(url: str, retry_count: int = ...) -> bytes | None:
    """Downloads data from an url and returns it

    Args:
        url: The url to download (http, https)
        retry_count: The number of retries to attempt if the initial download fails.
                If retry_count is 0 the download will only be attempted once.

    Returns:
        The downloaded data, None is returned if the download fails
    """
    ...

def get_from(urls: list[str], retry_count: int = ...) -> bytes | None:
    """Downloads data from a list of urls and returns it

    Args:
        urls: The urls to download (http, https)
        retry_count: The number of retries to attempt if the initial download fails.
                If retry_count is 0 the download will only be attempted once.

    Returns:
        The downloaded data, None is returned if the download fails
    """
    ...

def cache_spacy() -> Path | None:
    """Downloads Spacy multilingual model and saves it the cache directory for further use"""
    ...

