"""
This type stub file was generated by pyright.
"""

from pathlib import Path

package_lock = ...
class IPackage:
    """A package, can be either installed locally or available from a remote package index.

    Attributes:
        package_path: The path to the installed package. None if not installed.

        package_version: The version of the package.

        argos_version: The version of Argos Translate the package is intended for.

        from_code: The code of the language the package translates from.

        from_name: Human readable name of the language the package translates from.

        to_code: The code of the language the package translates to.

        to_name: Human readable name of the language the package translates to.

        links: A list of links to download the package


    Packages are a zip archive of a directory with metadata.json
    in its root the .argosmodel file extension. By default, an
    OpenNMT CTranslate2 directory named model/ is expected in the root directory
    along with a sentencepiece model named sentencepiece.model or a bpe.model
    for tokenizing and Stanza data for sentence boundary detection.
    Packages may also optionally have a README.md in the root.

    from_code and to_code should be ISO 639 codes if applicable.

    Example metadata.json
    {
        "package_version": "1.0",
        "argos_version": "1.0",
        "from_code": "en",
        "from_name": "English",
        "to_code": "es",
        "to_name": "Spanish",
        "links": ["https://example.com/en_es.argosmodel"]
    }
    """
    code: str
    package_path: Path
    package_version: str
    argos_version: str
    from_code: str
    from_name: str
    from_codes: list
    to_code: str
    to_codes: list
    to_name: str
    links: list
    type: str
    languages: list
    dependencies: list
    source_languages: list
    target_languages: list
    links: list[str]
    def load_metadata_from_json(self, metadata): # -> None:
        """Loads package metadata from a JSON object.

        Args:
            metadata: A json object from json.load

        """
        ...
    
    def get_readme(self) -> str:
        """Returns the text of the README.md in this package.

        Returns:
            The text of the package README.md, None
                if README.md can't be read

        """
        ...
    
    def get_description(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class Package(IPackage):
    """An installed package"""
    def __init__(self, package_path: Path) -> None:
        """Create a new Package from path.

        Args:
            package_path: Path to installed package directory.

        """
        ...
    
    def update(self): # -> None:
        """Update the package if a newer version is available."""
        ...
    
    def get_readme(self) -> str | None:
        """Returns the text of the README.md in this package.

        Returns:
            The text of the package README.md, None
                if README.md can't be read

        """
        ...
    
    def get_description(self): # -> str | None:
        ...
    


def install_from_path(path: Path): # -> None:
    """Install a package file (zip archive ending in .argosmodel).

    Args:
        path: The path to the .argosmodel file to install.

    """
    ...

class AvailablePackage(IPackage):
    """A package available for download and installation"""
    def __init__(self, metadata) -> None:
        """Creates a new AvailablePackage from a metadata object"""
        ...
    
    def download(self) -> Path:
        """Downloads the AvailablePackage and returns its path"""
        ...
    
    def install(self): # -> None:
        ...
    
    def get_description(self): # -> str:
        ...
    


def uninstall(pkg: Package): # -> None:
    """Uninstalls a package.

    Args:
        pkg: The package to uninstall

    """
    ...

def get_installed_packages(path: Path = ...) -> list[Package]:
    """Return a list of installed Packages

    Looks for packages in <home>/.argos-translate/local/share/packages by
    default. Will also look in the directory specified
    in the ARGOS_PACKAGE_DIR environment variable
    if it is set.

    Args:
        path: Path to look for installed package directories in.
            Defaults to the path in settings module.

    """
    ...

def update_package_index(): # -> None:
    """Downloads remote package index"""
    ...

def get_available_packages() -> list[AvailablePackage]:
    """Returns a list of AvailablePackages from the package index."""
    ...

def argospm_package_name(pkg: IPackage) -> str:
    """Gets argospm name of an IPackage.

    Args:
        The package to get the name of.

    Returns:
        Package name for argospm
    """
    ...

def install_package_for_language_pair(from_code: str, to_code: str) -> bool:
    """Installs the necessary package to translate between a pair of languages

    Args:
        from_code (str): The ISO 639 code for the language being translated from
        to_code (str): The ISO 639 code for the language being translated to

    Returns:
        True if the package was installed successfully,
        False if the installation failed or was not possible
    """
    ...

def load_available_packages() -> list[Package]:
    """Deprecated 1.2, use get_available_packages"""
    ...

