"""
This type stub file was generated by pyright.
"""

from typing import List
from argostranslate.package import Package

def get_stanza_processors(lang_code: str, resources: dict) -> str:
    """Get appropriate processors for a language, including MWT if available."""
    ...

_cached_spacy_path: str | None = ...
class ISentenceBoundaryDetectionModel:
    pkg: Package
    def split_sentences(self, text: str) -> List[str]:
        ...
    


class SpacySentencizerSmall(ISentenceBoundaryDetectionModel):
    def __init__(self, pkg: Package) -> None:
        """
        Packaging specific spacy when "xx_sent_ud_sm" doesn't cover the language improves performances over stanza.
        Please use small models ".._core/web_sm" for consistency.
        """
        ...
    
    def split_sentences(self, text: str) -> List[str]:
        ...
    
    def __str__(self) -> str:
        ...
    


class StanzaSentencizer(ISentenceBoundaryDetectionModel):
    LANGUAGE_CODE_MAPPING = ...
    def __init__(self, pkg: Package) -> None:
        ...
    
    def split_sentences(self, text: str) -> List[str]:
        ...
    
    def __str__(self) -> str:
        ...
    


fewshot_prompt = ...
DETECT_SENTENCE_BOUNDARIES_TOKEN = ...
SENTENCE_BOUNDARY_TOKEN = ...
FEWSHOT_BOUNDARY_TOKEN = ...
def get_sbd_package() -> Package | None:
    ...

def generate_fewshot_sbd_prompt(input_text: str, sentence_guess_length: int = ...) -> str:
    ...

def parse_fewshot_response(response_text: str) -> str | None:
    ...

def process_seq2seq_sbd(input_text: str, sbd_translated_guess: str) -> int:
    ...

def detect_sentence(input_text: str, sbd_translation, sentence_guess_length: int = ...) -> int:
    """Given input text, return the index after the end of the first sentence.

    Args:
        input_text: The text to detect the first sentence of.
        sbd_translation: An ITranslation for detecting sentences.
        sentence_guess_length: Estimated number of chars > than most sentences.

    Returns:
        The index of the character after the end of the sentence.
                -1 if not found.
    """
    ...

