"""
This type stub file was generated by pyright.
"""

from argostranslate.translate import ITranslation

class ITag:
    """Represents a tag tree

    Attributes:
        children: List of ITags and strs representing
                the children of the tag (empty list if no children)
        translateable: If translateable is False then a tag and its children
                should not be translated
    """
    translateable: bool
    def text(self) -> str:
        """The combined text of all of the children

        Returns:
            Combined text
        """
        ...
    
    def __str__(self) -> str:
        ...
    


class Tag(ITag):
    def __init__(self, children: ITag | str, translateable: bool = ...) -> None:
        ...
    
    def text(self) -> str:
        ...
    


def depth(tag: ITag | str) -> int:
    """Returns the depth of an ITag or str.

    A str has depth 0, ITag([]) has depth 0, ITag(['str']) has depth 1.

    Args:
        tag: The ITag or string to get the depth of.
    """
    ...

def translate_preserve_formatting(underlying_translation: ITranslation, input_text: str) -> str:
    """Translates but preserves a space if it exists on either end of translation.
    Args:
        underlying_translation : The translation to apply
        input_text: The text to translate
    Returns:
        The translated text
    """
    ...

def inject_tags_inference(underlying_translation: ITranslation, tag: ITag) -> ITag | None:
    """Returns translated tag tree with injection tags, None if not possible

    tag is only modified in place if tag injection is successful.

    Args:
        underlying_translation: The translation to apply to the tags.
        tag: A depth=2 tag tree to attempt injection on.

    Returns:
        A translated version of tag, None if not possible to tag inject
    """
    class InjectionTag:
        """

        Attributes:
            text: The text of the tag
            tag: The depth 1 ITag it represents
            injection_index: The index in the outer translated string that
                    this tag can be injected into.
        """
        ...
    
    

def translate_tags(underlying_translation: ITranslation, tag: ITag | str) -> ITag | str:
    """Translate an ITag or str

    Recursively takes either an ITag or a str, modifies it in place, and returns the translated tag tree

    Args:
        underlying_translation: The translation to apply
        tag: The tag tree to translate

    Returns:
        The translated tag tree
    """
    ...

