"""
This type stub file was generated by pyright.
"""

import functools
from typing import List
from ctranslate2 import Translator
from argostranslate import sbd
from argostranslate.models import ILanguageModel
from argostranslate.package import Package

class Hypothesis:
    """Represents a translation hypothesis

    Attributes:
        value: The hypothetical translation value
        score: The score representing the quality of the translation
    """
    value: str
    score: float
    def __init__(self, value: str, score: float) -> None:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class ITranslation:
    """Represents a translation between two Languages

    Attributes:
        from_lang: The Language this Translation translates from.
        to_lang: The Language this Translation translates to.

    """
    from_lang: Language
    to_lang: Language
    def translate(self, input_text: str) -> str:
        """Translates a string from self.from_lang to self.to_lang

        Args:
            input_text: The text to be translated.

        Returns:
            input_text translated.

        """
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...) -> list[Hypothesis]:
        """Translates a string from self.from_lang to self.to_lang

        Args:
            input_text: The text to be translated.
            num_hypotheses: Number of hypothetical results expected

        Returns:
            List of translation hypotheses

        """
        ...
    
    @staticmethod
    def split_into_paragraphs(input_text: str) -> list[str]:
        """Splits input_text into paragraphs and returns a list of paragraphs.

        Args:
            input_text: The text to be split.

        Returns:
            A list of paragraphs.

        """
        ...
    
    @staticmethod
    def combine_paragraphs(paragraphs: list[str]) -> str:
        """Combines a list of paragraphs together.

        Args:
            paragraphs: A list of paragraphs.

        Returns:
            list of n paragraphs combined into one string.

        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class Language:
    """Represents a language that can be translated from/to.

    Attributes:
        code: The code representing the language.
        name: The human-readable name of the language.
        translations_from: A list of the translations
            that translate from this language.
        translations_to: A list of the translations
            that translate to this language

    """
    translations_from: list[ITranslation] = ...
    translations_to: list[ITranslation] = ...
    def __init__(self, code: str, name: str) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def get_translation(self, to: Language) -> ITranslation | None:
        """Gets a translation from this Language to another Language.

        Args:
            to: The Language to look for a Translation to.

        Returns:
            A valid Translation if there is one in translations_from
                else None.

        """
        ...
    


class PackageTranslation(ITranslation):
    """A Translation that is installed with a package"""
    def __init__(self, from_lang: Language, to_lang: Language, pkg: Package) -> None:
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...) -> list[Hypothesis]:
        ...
    


class IdentityTranslation(ITranslation):
    """A Translation that doesn't modify input_text."""
    def __init__(self, lang: Language) -> None:
        """Creates an IdentityTranslation.

        Args:
            lang: The Language this Translation translates
                from and to.

        """
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...): # -> list[Hypothesis]:
        ...
    


class CompositeTranslation(ITranslation):
    """A ITranslation that is performed by chaining two Translations

    Attributes:
        t1: The first Translation to apply.
        t2: The second Translation to apply.

    """
    t1: ITranslation
    t2: ITranslation
    from_lang: Language
    to_lang: Language
    def __init__(self, t1: ITranslation, t2: ITranslation) -> None:
        """Creates a CompositeTranslation.

        Args:
            t1: The first Translation to apply.
            t2: The second Translation to apply.
        """
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...) -> list[Hypothesis]:
        ...
    


class CachedTranslation(ITranslation):
    """Caches a translation to improve performance.

    This is done by splitting up the text passed for translation
    into paragraphs and translating each paragraph individually.
    A hash of the paragraphs and their corresponding translations
    are saved from the previous translation and used to improve
    performance on the next one. This is especially useful if you
    are repeatedly translating nearly identical text with a small
    change at the end of it.

    """
    underlying: ITranslation
    from_lang: Language
    to_lang: Language
    cache: dict
    def __init__(self, underlying: ITranslation) -> None:
        """Creates a CachedTranslation.

        Args:
            underlying: The underlying translation to cache.
        """
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...) -> list[Hypothesis]:
        ...
    


class RemoteTranslation(ITranslation):
    """A translation provided by a remote LibreTranslate server"""
    from_lang: Language
    to_lang: Language
    def __init__(self, from_lang: Language, to_lang: Language, api) -> None:
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...) -> list[Hypothesis]:
        """LibreTranslate only supports single hypotheses.

        A list of length num_hypotheses will be returned with identical hypotheses.
        """
        ...
    


LibreTranslateTranslation = RemoteTranslation
class FewShotTranslation(ITranslation):
    """A translation performed with a few shot language model"""
    from_lang: Language
    to_lang: Language
    language_model: ILanguageModel
    def __init__(self, from_lang: Language, to_lang: Language, language_model: ILanguageModel) -> None:
        ...
    
    def hypotheses(self, input_text: str, num_hypotheses: int = ...) -> list[Hypothesis]:
        ...
    


def apply_packaged_translation(pkg: Package, input_text: str, translator: Translator, sentencizer: sbd.ISentenceBoundaryDetectionModel, num_hypotheses: int = ...) -> list[Hypothesis]:
    """Applies the translation in pkg to translate input_text.

    Args:
        pkg: The package that provides the translation.
        input_text: The text to be translated.
        translator: The CTranslate2 Translator
        sentencizer: The Sentence Boundary Detection package
        num_hypotheses: The number of hypotheses to generate

    Returns:
        A list of Hypotheses objects for translated input_text.
    """
    ...

class InstalledTranslate:
    """
    Global storage of instances of the CachedTranslation class by unique keys.
    To avoid creating unnecessary objects in memory.
    """
    package_key: str
    cached_translation: CachedTranslation
    ...


installed_translates: List[InstalledTranslate] = ...
@functools.lru_cache()
def get_installed_languages() -> list[Language]:
    """Returns a list of Languages installed from packages"""
    ...

def load_installed_languages() -> list[Language]:
    """Deprecated 1.2, use get_installed_languages"""
    ...

def get_language_from_code(code: str) -> Language | None:
    """Gets a language object from a code

    An exception will be thrown if an installed language with this
    code can not be found.

    Args:
        code: The ISO 639 code of the language

    Returns:
        The language object
    """
    ...

def get_translation_from_codes(from_code: str, to_code: str) -> ITranslation:
    """Gets a translation object from codes for from and to languages

    An exception will be thrown if an installed translation between the from lang
    and to lang can not be found.

    Args:
        from_code: The ISO 639 code of the source language
        to_code: The ISO 639 code of the target language

    Returns:
        The translation object
    """
    ...

def translate(q: str, from_code: str, to_code: str) -> str:
    """Translate a string of text

    Args:
        q: The text to translate
        from_code: The ISO 639 code of the source language
        to_code: The ISO 639 code of the target language

    Returns:
        The translated text
    """
    ...

