"""
This type stub file was generated by pyright.
"""

from argostranslate import settings

logger = ...
if settings.debug:
    std_out_stream_handler = ...
def debug(*argv): # -> None:
    """Debug level log"""
    ...

def info(*argv): # -> None:
    """Info level log"""
    ...

def warning(*argv): # -> None:
    """Warning level log"""
    ...

def error(*argv): # -> None:
    """Error level log"""
    ...

